-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.1.30-MariaDB - mariadb.org binary distribution
-- SO del servidor:              Win32
-- HeidiSQL Versión:             10.1.0.5464
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Volcando estructura de base de datos para pepsidb
CREATE DATABASE IF NOT EXISTS `pepsidb` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `pepsidb`;

-- Volcando estructura para tabla pepsidb.estados
CREATE TABLE IF NOT EXISTS `estados` (
  `EDO_ID` int(1) NOT NULL AUTO_INCREMENT,
  `EDO_NOMBRE` varchar(30) NOT NULL,
  `EDO_CREADO_POR` int(8) NOT NULL,
  `EDO_CREADO_FECHA` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `EDO_MODIF_POR` int(8) DEFAULT NULL,
  `EDO_MODIF_FECHA` datetime DEFAULT NULL,
  PRIMARY KEY (`EDO_ID`),
  UNIQUE KEY `EDO_NOMBRE` (`EDO_NOMBRE`),
  KEY `EDO-CREADO POR` (`EDO_CREADO_POR`),
  KEY `EDO-MODIFICADO POR` (`EDO_MODIF_POR`),
  CONSTRAINT `EDO-CREADO POR` FOREIGN KEY (`EDO_CREADO_POR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE,
  CONSTRAINT `EDO-MODIFICADO POR` FOREIGN KEY (`EDO_MODIF_POR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

-- Volcando datos para la tabla pepsidb.estados: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `estados` DISABLE KEYS */;
INSERT INTO `estados` (`EDO_ID`, `EDO_NOMBRE`, `EDO_CREADO_POR`, `EDO_CREADO_FECHA`, `EDO_MODIF_POR`, `EDO_MODIF_FECHA`) VALUES
	(1, 'Activo', 1, '2019-03-04 12:02:30', NULL, NULL),
	(2, 'Inactivo', 1, '2019-03-04 12:16:40', NULL, NULL);
/*!40000 ALTER TABLE `estados` ENABLE KEYS */;

-- Volcando estructura para tabla pepsidb.forms
CREATE TABLE IF NOT EXISTS `forms` (
  `FORM_ID` int(12) NOT NULL AUTO_INCREMENT,
  `FORM_NOMBRE` varchar(50) NOT NULL,
  `FORM_INPUTS` varchar(2000) DEFAULT NULL,
  `FORM_LABELS` varchar(2000) DEFAULT NULL,
  `FORM_PLACEHOLDER` varchar(2000) DEFAULT NULL,
  `FORM_REQUIRED` varchar(1000) DEFAULT NULL,
  `FORM_DISABLED` varchar(1000) DEFAULT NULL,
  `FORM_REGEX` varchar(2000) DEFAULT NULL,
  `FORM_CREADO_POR` int(8) NOT NULL,
  `FORM_CREADO_FECHA` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `FORM_MODIF_POR` int(8) DEFAULT NULL,
  `FORM_ESTADO` int(1) NOT NULL DEFAULT '1',
  `FORM_MODIF_FECHA` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`FORM_ID`),
  UNIQUE KEY `FORM_NOMBRE` (`FORM_NOMBRE`),
  KEY `FORM-CREADO` (`FORM_CREADO_POR`),
  KEY `FORM-MODIFICADO` (`FORM_MODIF_POR`),
  KEY `FORM-ESTADO` (`FORM_ESTADO`),
  CONSTRAINT `FORM-CREADO` FOREIGN KEY (`FORM_CREADO_POR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE,
  CONSTRAINT `FORM-ESTADO` FOREIGN KEY (`FORM_ESTADO`) REFERENCES `estados` (`EDO_ID`) ON UPDATE CASCADE,
  CONSTRAINT `FORM-MODIFICADO` FOREIGN KEY (`FORM_MODIF_POR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Volcando datos para la tabla pepsidb.forms: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `forms` DISABLE KEYS */;
/*!40000 ALTER TABLE `forms` ENABLE KEYS */;

-- Volcando estructura para tabla pepsidb.incidencias
CREATE TABLE IF NOT EXISTS `incidencias` (
  `INC_ID` int(15) NOT NULL AUTO_INCREMENT,
  `INC_FORM` int(12) NOT NULL,
  `INC_CREADO_POR` int(8) NOT NULL,
  `INC_CREADO_FECHA` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `INC_ESCALADO_CON` int(8) NOT NULL,
  `INC_ESTADO` int(1) NOT NULL DEFAULT '1',
  `INC_SOLUCIONADO` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`INC_ID`),
  KEY `INC-FORMULARIO` (`INC_FORM`),
  KEY `INC-CREADO POR` (`INC_CREADO_POR`),
  KEY `INC-ESCALADO` (`INC_ESCALADO_CON`),
  KEY `INC-ESTADO` (`INC_ESTADO`),
  CONSTRAINT `INC-CREADO POR` FOREIGN KEY (`INC_CREADO_POR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE,
  CONSTRAINT `INC-ESCALADO` FOREIGN KEY (`INC_ESCALADO_CON`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE,
  CONSTRAINT `INC-ESTADO` FOREIGN KEY (`INC_ESTADO`) REFERENCES `estados` (`EDO_ID`) ON UPDATE CASCADE,
  CONSTRAINT `INC-FORMULARIO` FOREIGN KEY (`INC_FORM`) REFERENCES `forms` (`FORM_ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Volcando datos para la tabla pepsidb.incidencias: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `incidencias` DISABLE KEYS */;
/*!40000 ALTER TABLE `incidencias` ENABLE KEYS */;

-- Volcando estructura para tabla pepsidb.log_asistencia
CREATE TABLE IF NOT EXISTS `log_asistencia` (
  `LOGA_ID` int(15) NOT NULL AUTO_INCREMENT,
  `LOGA_USR` int(8) NOT NULL,
  `LOGA_INICIO` datetime DEFAULT NULL,
  `LOGA_FIN` datetime DEFAULT NULL,
  PRIMARY KEY (`LOGA_ID`),
  KEY `LOG USUARIO` (`LOGA_USR`),
  CONSTRAINT `LOG USUARIO` FOREIGN KEY (`LOGA_USR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Volcando datos para la tabla pepsidb.log_asistencia: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `log_asistencia` DISABLE KEYS */;
/*!40000 ALTER TABLE `log_asistencia` ENABLE KEYS */;

-- Volcando estructura para tabla pepsidb.roles
CREATE TABLE IF NOT EXISTS `roles` (
  `ROL_ID` int(1) NOT NULL AUTO_INCREMENT,
  `ROL_NOMBRE` varchar(30) NOT NULL,
  `ROL_CREADO_POR` int(8) NOT NULL,
  `ROL_CREADO_FECHA` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ROL_MODIF_POR` int(8) DEFAULT NULL,
  `ROL_MODIF_FECHA` datetime DEFAULT NULL,
  `ROL_ESTADO` int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ROL_ID`),
  UNIQUE KEY `ROL_NOMBRE` (`ROL_NOMBRE`),
  KEY `ROL-CREADO POR` (`ROL_CREADO_POR`),
  KEY `ROL-MODIFICADO POR` (`ROL_MODIF_POR`),
  KEY `RO-ESTADO` (`ROL_ESTADO`),
  CONSTRAINT `RO-ESTADO` FOREIGN KEY (`ROL_ESTADO`) REFERENCES `estados` (`EDO_ID`) ON UPDATE CASCADE,
  CONSTRAINT `ROL-CREADO POR` FOREIGN KEY (`ROL_CREADO_POR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE,
  CONSTRAINT `ROL-MODIFICADO POR` FOREIGN KEY (`ROL_MODIF_POR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

-- Volcando datos para la tabla pepsidb.roles: ~3 rows (aproximadamente)
/*!40000 ALTER TABLE `roles` DISABLE KEYS */;
INSERT INTO `roles` (`ROL_ID`, `ROL_NOMBRE`, `ROL_CREADO_POR`, `ROL_CREADO_FECHA`, `ROL_MODIF_POR`, `ROL_MODIF_FECHA`, `ROL_ESTADO`) VALUES
	(1, 'Administrador', 1, '2019-03-04 12:07:35', NULL, NULL, 1),
	(2, 'Supervisor', 1, '2019-03-04 12:16:20', NULL, NULL, 1),
	(3, 'Guardia', 1, '2019-03-04 12:16:29', NULL, NULL, 1);
/*!40000 ALTER TABLE `roles` ENABLE KEYS */;

-- Volcando estructura para tabla pepsidb.users
CREATE TABLE IF NOT EXISTS `users` (
  `USR_ID` int(8) NOT NULL AUTO_INCREMENT,
  `USR_NOMBRE` varchar(50) NOT NULL,
  `USR_USERNAME` varchar(50) NOT NULL,
  `USR_AP_PATERNO` varchar(50) NOT NULL,
  `USR_AP_MATERNO` varchar(50) DEFAULT NULL,
  `USR_ROL` int(1) NOT NULL DEFAULT '1',
  `USR_JEFE_DIRECTO` int(8) NOT NULL,
  `USR_PASSWORD` varchar(60) NOT NULL,
  `USR_CREADO_POR` int(8) NOT NULL,
  `USR_CREADO_FECHA` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `USR_MODIF_POR` int(8) DEFAULT NULL,
  `USR_MODIF_FECHA` datetime DEFAULT NULL,
  `USR_ESTADO` int(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`USR_ID`),
  UNIQUE KEY `USR_USERNAME` (`USR_USERNAME`),
  KEY `JEFE DIRECTO` (`USR_JEFE_DIRECTO`),
  KEY `CREADO POR` (`USR_CREADO_POR`),
  KEY `MODIFICADO POR` (`USR_MODIF_POR`),
  KEY `ESTADO` (`USR_ESTADO`),
  KEY `ROL` (`USR_ROL`),
  CONSTRAINT `CREADO POR` FOREIGN KEY (`USR_CREADO_POR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE,
  CONSTRAINT `ESTADO` FOREIGN KEY (`USR_ESTADO`) REFERENCES `estados` (`EDO_ID`) ON UPDATE CASCADE,
  CONSTRAINT `JEFE DIRECTO` FOREIGN KEY (`USR_JEFE_DIRECTO`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE,
  CONSTRAINT `MODIFICADO POR` FOREIGN KEY (`USR_MODIF_POR`) REFERENCES `users` (`USR_ID`) ON UPDATE CASCADE,
  CONSTRAINT `ROL` FOREIGN KEY (`USR_ROL`) REFERENCES `roles` (`ROL_ID`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

-- Volcando datos para la tabla pepsidb.users: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`USR_ID`, `USR_NOMBRE`, `USR_USERNAME`, `USR_AP_PATERNO`, `USR_AP_MATERNO`, `USR_ROL`, `USR_JEFE_DIRECTO`, `USR_PASSWORD`, `USR_CREADO_POR`, `USR_CREADO_FECHA`, `USR_MODIF_POR`, `USR_MODIF_FECHA`, `USR_ESTADO`) VALUES
	(1, 'admin', 'sysadmin', 'system', NULL, 1, 1, 'password', 1, '2019-03-04 11:55:49', NULL, NULL, 1);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
